# See https://fly.io/docs/reference/configuration/ for reference

app = "uma-world-valhalla"
primary_region = "cdg"

[build]
  image = "ghcr.io/gis-ops/docker-valhalla/valhalla:latest"

[mounts]
  source = "uma_world_valhalla"
  destination = "/custom_files"

[env]
  tile_urls = "https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf"
  use_tiles_ignore_pbf = "True"
  force_rebuild = "False"
  build_elevation = "True"
  build_admins = "False"
  build_timezones = "True"
  build_transit = "False"
  build_tar = "True"
  serve_tiles = "True"
  tileset_name = "uma_world_valhalla_tiles"

# [http_service]
#   internal_port = 8002
#   force_https = true
#   auto_stop_machines = false
#   auto_start_machines = false
#   min_machines_running = 1
#   [[http_service.checks]]
#     grace_period = "15m"
#     interval = "5m"
#     method = "GET"
#     timeout = "5s"
#     path = "/status"

# note: any kind of HTTP handler seems to fail with a Malformed HTTP Request error
# right now. Local server works fine. Will figure out later

[[services]]
  internal_port = 8002
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = 80
    handlers = []
    force_https = false
  [[services.http_checks]]
    grace_period = "15m"
    interval = "10m"
    method = "GET"
    path = "/status"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = true
